In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split,RandomizedSearchCV,GridSearchCV
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.tree import DecisionTreeRegressor,DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor,RandomForestClassifier,AdaBoostClassifier
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.metrics import accuracy_score,r2_score,classification_report,confusion_matrix
import joblib
import pickle

In [2]:
df=pd.read_csv(r'C:\Users\amank\Downloads\Learning_day_1\DataScience_salaries_2025.csv')
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025,MI,FT,Research Scientist,208000,USD,208000,US,0,US,M
1,2025,MI,FT,Research Scientist,147000,USD,147000,US,0,US,M
2,2025,SE,FT,Research Scientist,173000,USD,173000,US,0,US,M
3,2025,SE,FT,Research Scientist,117000,USD,117000,US,0,US,M
4,2025,MI,FT,AI Engineer,100000,USD,100000,US,100,US,M

In [3]:
df.drop(columns=['salary','salary_currency'],inplace=True)

In [4]:
df.head()

,work_year,experience_level,employment_type,job_title,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025,MI,FT,Research Scientist,208000,US,0,US,M
1,2025,MI,FT,Research Scientist,147000,US,0,US,M
2,2025,SE,FT,Research Scientist,173000,US,0,US,M
3,2025,SE,FT,Research Scientist,117000,US,0,US,M
4,2025,MI,FT,AI Engineer,100000,US,100,US,M

In [5]:
df.isnull().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(46975)

In [7]:
df.drop_duplicates()

,work_year,experience_level,employment_type,job_title,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025,MI,FT,Research Scientist,208000,US,0,US,M
1,2025,MI,FT,Research Scientist,147000,US,0,US,M
2,2025,SE,FT,Research Scientist,173000,US,0,US,M
3,2025,SE,FT,Research Scientist,117000,US,0,US,M
4,2025,MI,FT,AI Engineer,100000,US,100,US,M
...,...,...,...,...,...,...,...,...,...
93592,2020,SE,FT,Data Scientist,412000,US,100,US,L
93593,2021,MI,FT,Principal Data Scientist,151000,US,100,US,L
93594,2020,EN,FT,Data Scientist,105000,US,100,US,S
93595,2020,EN,CT,Business Data Analyst,100000,US,100,US,L
93596,2021,SE,FT,Data Scientist,94665,IN,50,IN,L

In [8]:
label=LabelEncoder()

In [9]:
df['encoded_experience_level']=label.fit_transform(df['experience_level'])
df['encoded_employment_type']=label.fit_transform(df['employment_type'])
df['encoded_job_title']=label.fit_transform(df['job_title'])
df['encoded_employee_residence']=label.fit_transform(df['employee_residence'])
df['encoded_company_location']=label.fit_transform(df['company_location'])
df['encoded_company_size']=label.fit_transform(df['company_size'])

In [10]:
df.head()

,work_year,experience_level,employment_type,job_title,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,encoded_experience_level,encoded_employment_type,encoded_job_title,encoded_employee_residence,encoded_company_location,encoded_company_size
0,2025,MI,FT,Research Scientist,208000,US,0,US,M,2,2,282,89,84,1
1,2025,MI,FT,Research Scientist,147000,US,0,US,M,2,2,282,89,84,1
2,2025,SE,FT,Research Scientist,173000,US,0,US,M,3,2,282,89,84,1
3,2025,SE,FT,Research Scientist,117000,US,0,US,M,3,2,282,89,84,1
4,2025,MI,FT,AI Engineer,100000,US,100,US,M,2,2,4,89,84,1

In [11]:
df.drop(columns=['experience_level','employment_type','job_title','employee_residence','company_location','company_size'],inplace=True)

In [12]:
x=df[['work_year','salary_in_usd','remote_ratio','encoded_experience_level','encoded_employment_type','encoded_job_title','encoded_employee_residence','encoded_company_location','encoded_company_size']]
y=df['salary_in_usd']

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [14]:
best_param={'n_estimators':[100,200,300,400,500],'max_depth':[5,10,15,20,25]}

In [ ]:
model=RandomForestRegressor(random_state=42)

In [ ]:
grid_search=GridSearchCV(estimator=model,
                         
                         param_grid=best_param,

                         cv=5,

                         n_jobs=-1,
                         
                         verbose=2)

In [ ]:
grid_search.fit(x_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits

In [ ]:
best_model=grid_search,best_estimator_

In [ ]:
y_pred=grid_search.predict(x_train)
r2_score(y_train,y_pred)

In [ ]:
y_pred=grid_search(x_test)
r2_score(y_test,y_pred)

In [ ]:
joblib.dump(grid_search,'datascience_salary.pkl')